ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:figure-caption!:

== Bio:

*A N M Bazlur Rahman* works at https://www.contrastsecurity.com/[Contrast Security] as a Sr. Software Engineer. He has more than ten years of professional experience in the software industry, predominantly in Java and Java-related technologies. Recently, he was honoured by being given the title of https://twitter.com/Java_Champions/status/1523728715368509440[ Java Champion].

Outside of his regular work hours, he loves to mentor, write, speak at conferences, and contribute to open-source projects. He is the founder and current moderator of thehttps://jugbd.org/[ Java User Group in Bangladesh]. He has organized meetups and conferences to share Java-related knowledge with the community since 2013. He was named Most Valuable Blogger (MVP) at https://dzone.com/users/1298119/bazlur_rahman.html[DZone], one of the most recognized technology publishers in the world. Besides DZone, he is an editor for the Java Queue at https://www.infoq.com/profile/A-N-M-Bazlur-Rahman/[InfoQ], another leading technology content publisher and conference organizer, and an editor at https://foojay.io/today/author/bazlur-rahman/[Foojay.io], a place for friends of OpenJDK. In addition, he has published https://www.rokomari.com/book/129165/java-programming[four books] about the Java programming language in Bengali; they were bestsellers in Bangladesh.

He earned his bachelor’s degree from the Institute of Information Technology, University of Dhaka, Bangladesh, in Information Technology, majoring in Software Engineering. He currently lives in Toronto, Canada.


== ✍️ Most recent blog posts

=== Foojay.io

<#list foojayPosts as post>

${post.title} (${(post.published).format('YYYY-MM-dd')})::
${post.excerpt}[...]
+
${post.link}[Read further^]

</#list>
